sudo: false
language: generic

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
    - libgmp-dev
    - cabal-install-1.24
    sources:
    - hvr-ghc
  postgresql: "9.4"

services:
- mysql

matrix:
  include:
  # ghc-7.8.4
  - env: STACK_YAML="stack-ghc-7.8.yaml"
  # ghc-7.10.3
  - env: STACK_YAML="stack-ghc-7.10.yaml"
  # ghc-ghc-8.0.2
  - env: STACK_YAML="stack-ghc-8.0.yaml"
  # ghc-ghc-8.2
  - env: STACK_YAML="stack-ghc-8.2.yaml"

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

before_script:
- cd groundhog-test/
- psql --username=postgres --file=init_postgresql.sql
- mysql --user=root < init_mysql.sql
- cd ..

# This line does all of the work: installs GHC if necessary, build the library,
# executables, and test suites, and runs the test suites. --no-terminal works
# around some quirks in Travis's terminal implementation.
script:
- stack test --no-terminal --install-ghc --flag groundhog-test:mysql --flag groundhog-test:postgresql --flag groundhog-test:sqlite
