language: haskell

ghc:
  - 7.8

before_install:
  - cd groundhog-test

install:
  - cabal install cabal-install
  - export PATH=~/.cabal/bin:$PATH
  - cabal install --only-dependencies --enable-tests -fsqlite -fpostgresql -fmysql

before_script:
  - psql --username=postgres --file=init_postgresql.sql
  - mysql --user=root < init_mysql.sql

script:
  - cabal configure --enable-tests -fsqlite -fpostgresql -fmysql
  - cabal build
  - cabal test --log=/dev/stdout
