flags:
  groundhog-test:
    mysql: true
    sqlite: true
    postgresql: true
extra-package-dbs: []
packages:
- groundhog/
- examples/
- groundhog-inspector/
- groundhog-postgresql/
- groundhog-sqlite/
- groundhog-th/
- groundhog-test/
extra-deps:
# Not on stackage
- mysql-0.1.4
- mysql-simple-0.4.0.0
# For older LTS
- aeson-pretty-0.8.2
- base-compat-0.9.1
- safe-exceptions-0.1.6.0
resolver: lts-7.18
